
import re
import sys

def convert_mysql_to_postgres(input_file, output_file):
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        try:
            with open(input_file, 'r', encoding='utf-16') as f:
                lines = f.readlines()
        except:
             with open(input_file, 'r', encoding='latin-1') as f:
                lines = f.readlines()
    except Exception as e:
        print(f"Error reading file: {e}")
        return

    output_lines = []
    output_lines.append("-- PostgreSQL Migration File Generated by Agent\n")
    
    # Pre-scan for table names to add DROP statements
    tables = []
    for line in lines:
        match = re.search(r'CREATE TABLE `?(\w+)`?', line)
        if match:
            tables.append(match.group(1))
    
    for table in tables:
        output_lines.append(f"DROP TABLE IF EXISTS {table} CASCADE;\n")
    
    output_lines.append("\n")

    in_create_table = False
    in_insert = False
    
    for line in lines:
        original_line = line
        line = line.strip()
        if not line:
            continue
            
        # Skip comments unless in the middle of something? usually SQL comments are separate lines
        if (line.startswith('--') or line.startswith('/*')) and not in_create_table and not in_insert:
            continue
            
        # Skip SET statements
        if (line.startswith('SET ') or line.startswith('START TRANSACTION') or line.startswith('COMMIT')) and not in_create_table and not in_insert:
            continue

        # CREATE TABLE start
        if line.startswith('CREATE TABLE'):
            in_create_table = True
            match = re.search(r'CREATE TABLE `?(\w+)`?', line)
            line = re.sub(r'CREATE TABLE `?(\w+)`?', r'CREATE TABLE \1', line)
            output_lines.append(line + "\n")
            continue
            
        # CREATE TABLE body
        if in_create_table:
            if line.startswith(') ENGINE='):
                in_create_table = False
                output_lines.append(");\n\n")
                continue
            
            # Process columns
            line = re.sub(r'`(\w+)`', r'\1', line)
            
            # Data types
            line = re.sub(r'\bint\(\d+\)', 'INTEGER', line, flags=re.IGNORECASE)
            line = re.sub(r'\btinyint\(\d+\)', 'SMALLINT', line, flags=re.IGNORECASE)
            line = re.sub(r'\bdatetime\b', 'TIMESTAMP', line, flags=re.IGNORECASE)
            line = re.sub(r'\btimestamp\b', 'TIMESTAMP', line, flags=re.IGNORECASE)
            line = re.sub(r'\bdouble\b', 'DOUBLE PRECISION', line, flags=re.IGNORECASE)
            line = re.sub(r'\bfloat\b', 'REAL', line, flags=re.IGNORECASE)
            line = re.sub(r'\bdecimal', 'DECIMAL', line, flags=re.IGNORECASE)
            
            # AUTO_INCREMENT -> SERIAL
            if 'AUTO_INCREMENT' in line:
                line = line.replace('AUTO_INCREMENT', '')
                line = re.sub(r'\bINTEGER\b', 'SERIAL', line, flags=re.IGNORECASE)
            
            # ENUM handling
            enum_match = re.search(r"enum\((.*?)\)", line, re.IGNORECASE)
            if enum_match:
                full_enum = enum_match.group(0)
                enum_values = enum_match.group(1)
                col_match = re.search(r'^(\w+)', line)
                if col_match:
                     col_name = col_match.group(1)
                     line = line.replace(full_enum, f"TEXT CHECK ({col_name} IN ({enum_values}))")

            # Defaults
            line = line.replace('current_timestamp()', 'CURRENT_TIMESTAMP')
            
            output_lines.append(line + "\n")
            continue

        # INSERT INTO start
        if line.startswith('INSERT INTO'):
            in_insert = True
            # Remove backticks
            line = re.sub(r'`(\w+)`', r'\1', line)
            
            # Unescape MySQL string content
            
            # Handle newlines first
            line = line.replace("\\r\\n", "\n").replace("\\n", "\n")
            
            # Remove standalone \r (escaped)
            line = line.replace("\\r", "")
            
            # Replace \' with '' (SQL standard escape)
            line = line.replace("\\'", "''")
            
            # Replace \" with " (Postgres doesn't escape double quotes)
            line = line.replace('\\"', '"')
            
            # Handle invalid dates
            line = line.replace("'0000-00-00 00:00:00'", "NULL")

            # Remove ANY remaining backslashes (Artifacts)
            line = line.replace("\\", "")
            
            output_lines.append(line + "\n")
            if line.endswith(';'):
                in_insert = False
            continue
            
        # INSERT body (values lines)
        if in_insert:
            # Same escaping logic
            line = line.replace("\\r\\n", "\n").replace("\\n", "\n")
            line = line.replace("\\r", "")
            line = line.replace("\\'", "''")
            line = line.replace('\\"', '"')
            line = line.replace("'0000-00-00 00:00:00'", "NULL")
            
            # Remove ANY remaining backslashes
            line = line.replace("\\", "")
            
            output_lines.append(line + "\n")
            if line.endswith(';'):
                in_insert = False
            continue

        # ALTER TABLE
        if line.startswith('ALTER TABLE'):
            line = re.sub(r'`(\w+)`', r'\1', line)
            
            if "ADD PRIMARY KEY" in line:
                output_lines.append(line + ";\n")
            elif "ADD KEY" in line:
                match = re.search(r'ALTER TABLE (\w+) ADD KEY (\w+) \((.*?)\)', line)
                if match:
                    tbl, idx, col = match.groups()
                    output_lines.append(f"CREATE INDEX {idx} ON {tbl} ({col});\n")
            elif "ADD CONSTRAINT" in line:
                output_lines.append(line + ";\n")
                
            continue

    # Append Sequence Reset Logic
    output_lines.append("\n-- Reset Sequences for SERIAL columns\n")
    # We detected tables; we assume standard naming convention table_id_seq if we used SERIAL
    # But wait, we didn't track which tables use SERIAL in the loop accurately enough (some logic uses re.sub).
    # However, we know the tables from the pre-scan: recipes, ratings, admin_requests, reports, submission_requests, admin_chat_messages
    # We can just blindly try to reset valid sequences. 
    # Or, smarter: In the loop, when we sub 'SERIAL', we know the table.
    
    # Hardcoded known tables is safer for this specific task
    known_tables = ['recipes', 'ratings', 'admin_requests', 'reports', 'submission_requests', 'admin_chat_messages']
    for table in known_tables:
         # Check if table was actually in the input (it is in 'tables' list from pre-scan)
         if table in tables:
             output_lines.append(f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), COALESCE((SELECT MAX(id) + 1 FROM {table}), 1), false);\n")


    with open(output_file, 'w', encoding='utf-8') as f:
        f.writelines(output_lines)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python convert_schema.py input.sql output.sql")
    else:
        convert_mysql_to_postgres(sys.argv[1], sys.argv[2])
